// Generates public/sitemap.xml, public/404.html, public/site.webmanifest, and
// public/robots.txt from the configured base path + portfolio data. Runs
// before `vite build` (see package.json scripts).
//
// Env:
//   VITE_BASE_PATH   – e.g. "/nebula-shift-dev/" (must start and end with /)
//   VITE_SITE_URL    – public origin + base, no trailing slash

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const rawBase = process.env.VITE_BASE_PATH ?? "/nebula-shift-dev/";
const basePath = rawBase.endsWith("/") ? rawBase : `${rawBase}/`;
const siteUrl = (
  process.env.VITE_SITE_URL ?? "https://abikarthick-412.github.io/nebula-shift-dev"
).replace(/\/$/, "");

// pathSegmentsToKeep = number of non-empty segments in the base.
// "/nebula-shift-dev/" → 1, "/" → 0.
const segments = basePath.split("/").filter(Boolean);
const pathSegmentsToKeep = segments.length;

const out = (p) => resolve(root, "public", p);
mkdirSync(resolve(root, "public"), { recursive: true });

// ── Project IDs (parsed directly from src/data/portfolio.ts) ────────────────
// Match shape unique to Project entries: id → title → category within ~200 chars.
const portfolioSrc = readFileSync(resolve(root, "src/data/portfolio.ts"), "utf8");
const projectIds = [
  ...portfolioSrc.matchAll(
    /^\s*id:\s*"([a-z0-9-]+)"\s*,\s*\n\s*title:\s*"[^"]+",\s*\n\s*category:/gm,
  ),
].map((m) => m[1]);

// ── sitemap.xml ─────────────────────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10);
const urls = [
  { loc: `${siteUrl}/`, changefreq: "weekly", priority: "1.0" },
  ...projectIds.map((id) => ({
    loc: `${siteUrl}/projects/${id}`,
    changefreq: "monthly",
    priority: "0.7",
  })),
];
const sitemap = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
  ...urls.map(
    (u) =>
      `  <url><loc>${u.loc}</loc><lastmod>${today}</lastmod><changefreq>${u.changefreq}</changefreq><priority>${u.priority}</priority></url>`,
  ),
  `</urlset>`,
  ``,
].join("\n");
writeFileSync(out("sitemap.xml"), sitemap);

// ── robots.txt ──────────────────────────────────────────────────────────────
writeFileSync(
  out("robots.txt"),
  `User-agent: *\nAllow: /\n\nSitemap: ${siteUrl}/sitemap.xml\n`,
);

// ── site.webmanifest ────────────────────────────────────────────────────────
const manifest = {
  name: "Abikarthick G — Game Developer Portfolio",
  short_name: "Abikarthick G",
  description: "Unity game developer, gameplay programmer, and game designer portfolio.",
  start_url: basePath,
  scope: basePath,
  display: "standalone",
  background_color: "#0b0b13",
  theme_color: "#0b0b13",
  icons: [{ src: "favicon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" }],
};
writeFileSync(out("site.webmanifest"), JSON.stringify(manifest, null, 2) + "\n");

// ── 404.html (spa-github-pages, pathSegmentsToKeep injected) ────────────────
const notFound = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Redirecting…</title>
    <script>
      // Generated by scripts/generate-static.mjs from VITE_BASE_PATH.
      var pathSegmentsToKeep = ${pathSegmentsToKeep};
      var l = window.location;
      l.replace(
        l.protocol + "//" + l.hostname + (l.port ? ":" + l.port : "") +
          l.pathname.split("/").slice(0, 1 + pathSegmentsToKeep).join("/") +
          "/?/" +
          l.pathname.slice(1).split("/").slice(pathSegmentsToKeep).join("/").replace(/&/g, "~and~") +
          (l.search ? "&" + l.search.slice(1).replace(/&/g, "~and~") : "") +
          l.hash
      );
    </script>
  </head>
  <body></body>
</html>
`;
writeFileSync(out("404.html"), notFound);

console.log(
  `[generate-static] base=${basePath} siteUrl=${siteUrl} projects=${projectIds.length}`,
);
